[package]
name = "cursh"
version = "0.1.0"
edition = "2021"
description = "Cursh - curry shell commands"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.2.1"
colored = "2.0.0"
regex = "1.6.0"
tempfile = "3.3.0"
